# -*- coding: utf-8 -*-
"""day_13_DBSCAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c25ixrFZAlW7Y2qTaQyyhj27mHUtWD51
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import pi
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN

def points_in_circum(radius, n_points):
    angles = np.linspace(0, 2 * pi, n_points, endpoint=False)
    x = radius * np.cos(angles)
    y = radius * np.sin(angles)
    return np.c_[x, y]

np.random.seed(42)

circle1 = points_in_circum(20, 200) + np.random.normal(scale=1.0, size=(200, 2))
circle2 = points_in_circum(40, 200) + np.random.normal(scale=1.0, size=(200, 2))
circle3 = points_in_circum(60, 200) + np.random.normal(scale=1.0, size=(200, 2))

noise = np.random.uniform(low=-70, high=70, size=(60, 2))

data = np.vstack([circle1, circle2, circle3, noise])
df = pd.DataFrame(data, columns=[0, 1])

plt.figure(figsize=(6, 6))
plt.scatter(df[0], df[1], s=15)
plt.title("Sample Data (Concentric Circles + Noise)", fontsize=16)
plt.xlabel("Feature 1", fontsize=12)
plt.ylabel("Feature 2", fontsize=12)
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(df[[0, 1]])
df["kmeans_labels"] = kmeans.labels_

colors = ["purple", "red", "blue", "green"]

plt.figure(figsize=(6, 6))
plt.scatter(
    df[0],
    df[1],
    c=df["kmeans_labels"],
    cmap=plt.cm.colors.ListedColormap(colors),
    s=15
)
plt.title("K-Means Clustering", fontsize=20)
plt.xlabel("Feature 1", fontsize=14)
plt.ylabel("Feature 2", fontsize=14)
plt.show()

agg_model = AgglomerativeClustering(n_clusters=4, metric="euclidean")
agg_model.fit(df[[0, 1]])
df["hclust_labels"] = agg_model.labels_

plt.figure(figsize=(6, 6))
plt.scatter(
    df[0],
    df[1],
    c=df["hclust_labels"],
    cmap=plt.cm.colors.ListedColormap(colors),
    s=15
)
plt.title("Hierarchical (Agglomerative) Clustering", fontsize=20)
plt.xlabel("Feature 1", fontsize=14)
plt.ylabel("Feature 2", fontsize=14)
plt.show()

dbscan = DBSCAN(eps=30, min_samples=6)
dbscan.fit(df[[0, 1]])
df["dbscan_labels"] = dbscan.labels_
print(df["dbscan_labels"].value_counts())

plt.figure(figsize=(6, 6))
plt.scatter(
    df[0],
    df[1],
    c=df["dbscan_labels"],
    cmap=plt.cm.colors.ListedColormap(colors),
    s=15
)
plt.title("DBSCAN Clustering", fontsize=20)
plt.xlabel("Feature 1", fontsize=14)
plt.ylabel("Feature 2", fontsize=14)
plt.show()